# Generated by Django 4.2.18 on 2025-03-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("track", "0002_traceabilitydata_st6_result_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="traceabilitydata",
            name="part_number",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="traceabilitydata",
            unique_together={("part_number", "date")},
        ),
    ]
