# Generated by Django 4.2.18 on 2025-03-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("track", "0003_alter_traceabilitydata_part_number_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="traceabilitydata",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="traceabilitydata",
            name="part_number",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
