# Generated by Django 4.2.18 on 2026-05-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0006_traceabilitydata_st6_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='traceabilitydata',
            name='st1_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traceabilitydata',
            name='st2_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traceabilitydata',
            name='st3_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traceabilitydata',
            name='st4_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traceabilitydata',
            name='st5_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traceabilitydata',
            name='st6_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
